import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.h1}>Activities</h1>
        <hr className={styles.hr} />
        <ul className={styles.ul}>
          <li className={styles.li} onClick={() => router.push("/yoga")}>Yoga</li>
          <li className={styles.li}>Soccer</li>
          <li className={styles.li}>Merchandise</li>
        </ul>
      </main>
    </>
  )
}
